pipeline {
    agent any

    tools {
        maven "maven363"
    }
    environment {
    	workdir = "./spring-boot-samples/spring-boot-sample-web-ui"
        NEXUS_VERSION = 'nexus3'
        NEXUS_PROTOCOL = 'http'
        NEXUS_URL = "localhost:8081"
        NEXUS_REPOSITORY = "GrW"
        NEXUS_CREDENTIAL_ID = "6f6c7b81-b8ac-4229-a669-fd7701a03500"
    }

	stages {
		stage('SCM checkout') {
			steps{
				git branch: '2.1.x', url: 'https://github.com/miehhej/spring-boot.git'
			}
		}
    	stage("Build") {
        	steps {
				sh "mvn -DskipTests clean install -f ./spring-boot-samples/pom.xml"
			}
		}
		stage ('Upload to NEXUS') {
			steps {
				nexusArtifactUploader {
					nexusVersion('$env.NEXUS_VERSION')
                	protocol('$env.NEXUS_PROTOCOL')
                	nexusUrl('$env.NEXUS_URL')
	               	groupId('gr.id')
                	version('$BUILD_NUMBER')
                	repository('env.NEXUS_REPOSITORY')
                	credentialsId('env.NEXUS_CREDENTIAL_ID')
                	artifact {
                		artifactId('spring-boot-sample-web-ui')
                		type('jar')
                    	classifier('dev')
                    	file('./spring-boot-samples/spring-boot-sample-web-ui/target/spring-boot-sample-web-ui-2.1.16.BUILD-SNAPSHOT.jar')
                	}
               }
			}
		}
    }    
}



