pipeline {
    agent any

    tools {
        maven "maven363"
    }
    environment {
    	workdir = "./spring-boot-samples/spring-boot-sample-web-ui"
        NEXUS_VERSION = 'nexus3'
        NEXUS_PROTOCOL = 'http'
        NEXUS_URL = "localhost:8081"
        NEXUS_REPOSITORY = "GrW"
        NEXUS_CREDENTIAL_ID = "6f6c7b81-b8ac-4229-a669-fd7701a03500"
    }

	stages {
		stage('SCM checkout') {
			steps{
				git branch: '2.1.x', url: 'https://github.com/miehhej/spring-boot.git'
			}
		}
    	stage("Build") {
        	steps {
				sh "mvn -DskipTests clean install -f ./spring-boot-samples/pom.xml"
			}
		}
		stage ('Upload to NEXUS') {
			steps {
				nexusArtifactUploader {
					nexusVersion('nexus2')
        			protocol('http')
        			nexusUrl('localhost:8081')
        			groupId('sp.sd')
        			version('2.4')
        			repository('GrW')
                	credentialsId("6f6c7b81-b8ac-4229-a669-fd7701a03500")
                	artifact {
                		artifactId('spring-boot-sample-web-ui')
                		type('jar')
                    	classifier('debug')
                    	file:'./spring-boot-samples/spring-boot-sample-web-ui/target/spring-boot-sample-web-ui-2.1.16.BUILD-SNAPSHOT.jar'
                	}
               }
			}
		}
    }    
}



